apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: prod
type: Opaque
stringData:
  DATABASE_USER: "labuser"
  DATABASE_PASSWORD: "StrongPass123!"   # same as Terraform RDS user/pass
  SECRET_KEY: "any-random-app-secret"
