---
- name: Deploy application to EKS using Kubernetes manifests
  hosts: local
  vars:
    k8s_namespace: "prod"        # or "dev", whatever you decided
    k8s_dir: "../k8s"            # path to your k8s yaml files from ansible/ folder
  tasks:

    - name: Ensure Kubernetes namespace exists
      ansible.builtin.command:
        cmd: kubectl create namespace {{ k8s_namespace }}
      register: ns_result
      failed_when: ns_result.rc not in [0, 1]   # 0 = created, 1 = already exists
      changed_when: "'created' in ns_result.stdout"

    - name: Apply ConfigMap
      ansible.builtin.command:
        cmd: kubectl apply -n {{ k8s_namespace }} -f {{ k8s_dir }}/configmap.yaml

    - name: Apply Secret
      ansible.builtin.command:
        cmd: kubectl apply -n {{ k8s_namespace }} -f {{ k8s_dir }}/secret.yaml

    - name: Apply Deployment
      ansible.builtin.command:
        cmd: kubectl apply -n {{ k8s_namespace }} -f {{ k8s_dir }}/deployment.yaml

    - name: Apply Service
      ansible.builtin.command:
        cmd: kubectl apply -n {{ k8s_namespace }} -f {{ k8s_dir }}/service.yaml
